Document: cybrinth
Title: Debian cybrinth Manual
Author: <insert document author here>
Abstract: This manual describes what cybrinth is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cybrinth/cybrinth.sgml.gz

Format: postscript
Files: /usr/share/doc/cybrinth/cybrinth.ps.gz

Format: text
Files: /usr/share/doc/cybrinth/cybrinth.text.gz

Format: HTML
Index: /usr/share/doc/cybrinth/html/index.html
Files: /usr/share/doc/cybrinth/html/*.html
