/**
 * @file
 * @author James Dearing <dearingj@lifetime.oregonstate.edu>
 *
 * @section LICENSE
 * Copyright © 2012-2016.
 * This file is part of Cybrinth.
 *
 * Cybrinth is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Cybrinth is distributed 'as is' in the hope that it will be fun, but WITHOUT ANY WARRANTY; without even the implied warranty of TITLE, MERCHANTABILITY, COMPLETE DESTRUCTION OF EVIL MONSTERS, or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Cybrinth. If not, see <http://www.gnu.org/licenses/>.
 *
 * @section DESCRIPTION
 * The SettingsScreen class is responsible for drawing the settings screen and reacting to GUI events generated by said setting screen.
 */

#ifndef SETTINGSSCREEN_H
#define SETTINGSSCREEN_H

#include <irrlicht/irrlicht.h>

#include "SettingsManager.h"

class MainGame;

class SettingsScreen : public irr::IEventReceiver {
	public:
		SettingsScreen();
		virtual ~SettingsScreen();
		
		irr::video::SColor backgroundColor; //Used by MainGame when it calls driver->beginScene()
		irr::gui::IGUICheckBox* botsKnowSolutionCheckBox; //Can be checked/unchecked by SettingsManager based on chosen algorithm
		
		void changeToSettingsScreen();
		void changeFromSettingsScreen();
		
		void draw( irr::IrrlichtDevice* device );
		
		bool OnEvent( const irr::SEvent& event );
		
		void setButtonFont( irr::gui::IGUIFont* newTextFont );
		void setPointers( MainGame* newMainGame, irr::IrrlichtDevice* newDevice, irr::gui::IGUIFont* newButtonFont, irr::gui::IGUIFont* newTextFont, SettingsManager* newSettingsManager );
		void setTextFont( irr::gui::IGUIFont* newTextFont );
		void setupIconsAndStuff();
		
	protected:
	private:
		irr::gui::IGUICheckBox* alwaysServerCheckBox;
		irr::gui::IGUICheckBox* autoDetectResolutionCheckBox;
		
		irr::gui::IGUICheckBox* backgroundAnimationsCheckBox;
		void backToMenu();
		irr::gui::IGUIListBox* botAlgorithmListBox;
		irr::gui::IGUIStaticText* botAlgorithmText;
		irr::gui::IGUISpinBox* botMovementDelaySpinBox;
		irr::gui::IGUIStaticText* botMovementDelayText;
		irr::gui::IGUICheckBox* bpp16CheckBox;
		irr::gui::IGUICheckBox* bpp32CheckBox;
		irr::gui::IGUIStaticText* bppText;
		irr::gui::IGUICheckBox* burningsSoftwareCheckBox;
		irr::gui::IGUIFont* buttonFont;
		
		irr::gui::IGUIButton* cancelButton;
		
		irr::gui::IGUICheckBox* debugCheckBox;
		irr::IrrlichtDevice* device;
		irr::gui::IGUICheckBox* direct3D8CheckBox;
		irr::gui::IGUICheckBox* direct3D9CheckBox;
		irr::video::IVideoDriver* driver;
		irr::gui::IGUIStaticText* driverTypeText;
		
		irr::gui::IGUIEnvironment* environment;
		
		irr::gui::IGUICheckBox* fullscreenCheckBox;
		irr::gui::IGUISpinBox* fullscreenHeightSpinBox;
		irr::gui::IGUIStaticText* fullscreenResolutionText;
		irr::gui::IGUISpinBox* fullscreenWidthSpinBox;
		
		irr::gui::IGUITab* graphicsTab;
		enum gui_id_t : uint_fast8_t { BOTS_KNOW_SOLUTION_CHECKBOX_ID, BOT_MOVEMENT_DELAY_SPINBOX_ID, ALWAYS_SERVER_CHECKBOX_ID, NETWORK_PORT_SPINBOX_ID, NUM_BOTS_BAR_ID, NUM_BOTS_SPINBOX_ID, NUM_PLAYERS_SPINBOX_ID, NUM_PLAYERS_BAR_ID, FULLSCREEN_HEIGHT_SPINBOX_ID, FULLSCREEN_WIDTH_SPINBOX_ID, AUTODETECT_RESOLUTION_CHECKBOX_ID, MARK_TRAILS_CHECKBOX_ID, BACKGROUND_ANIMATIONS_CHECKBOX_ID, SHOW_BACKGROUNDS_CHECKBOX_ID, WINDOW_HEIGHT_SPINBOX_ID, WINDOW_WIDTH_SPINBOX_ID, DIRECT3D8_CHECKBOX_ID, DIRECT3D9_CHECKBOX_ID, OPENGL_CHECKBOX_ID, IRRLICHTSOFTWARE_CHECKBOX_ID, BURNINGSSOFTWARE_CHECKBOX_ID, CANCEL_ID, OK_ID, RESET_TO_DEFAULTS_ID, UNDO_CHANGES_ID, TAB_CONTROL_ID, PLAY_MUSIC_CHECKBOX_ID, VOLUME_BAR_ID, FULLSCREEN_CHECKBOX_ID, BPP16_CHECKBOX_ID, BPP32_CHECKBOX_ID, VSYNC_CHECKBOX_ID, BOT_ALGORITHM_LISTBOX_ID, DEBUG_CHECKBOX_ID, DO_NOT_USE_ID }; //I made these an enum because I'm too lazy to manually assign values to each one, so why not make the compiler do it?
		
		irr::gui::IGUICheckBox* irrlichtSoftwareCheckBox;
		
		MainGame* mainGame;
		irr::gui::IGUICheckBox* markTrailsCheckBox;
		irr::gui::IGUITab* miscTab;
		irr::gui::IGUITab* multiplayerTab;
		
		irr::gui::IGUIStaticText* networkPortText;
		irr::gui::IGUISpinBox* networkPortSpinBox;
		irr::gui::IGUIScrollBar* numBotsBar;
		irr::gui::IGUISpinBox* numBotsSpinBox;
		irr::gui::IGUIStaticText* numBotsText;
		irr::gui::IGUIScrollBar* numPlayersBar;
		irr::gui::IGUISpinBox* numPlayersSpinBox;
		irr::gui::IGUIStaticText* numPlayersText;
		
		irr::gui::IGUIButton* okButton;
		irr::gui::IGUICheckBox* openGLCheckBox;
		
		irr::gui::IGUICheckBox* playMusicCheckBox;
		
		void resetChangedSettings();
		irr::gui::IGUIButton* resetToDefaultsButton;
		void resetToDefaultSettings();
		irr::core::stringw restartNotice;
		
		void saveSettings();
		bool settingsChanged; //If no settings were changed, don't bother saving them.
		SettingsManager* settingsManager;
		irr::gui::IGUICheckBox* showBackgroundsCheckBox;
		irr::gui::IGUISkin* skin;
		irr::gui::IGUITab* soundTab;
		
		irr::gui::IGUITabControl* tabControl;
		irr::gui::IGUIFont* textFont;
		
		irr::gui::IGUIButton* undoChangesButton;
		
		irr::gui::IGUIScrollBar* volumeBar;
		irr::gui::IGUIStaticText* volumeText;
		irr::gui::IGUICheckBox* vsyncCheckBox;
		
		irr::gui::IGUIStaticText* windowSizeText;
		irr::gui::IGUISpinBox* windowHeightSpinBox;
		irr::gui::IGUISpinBox* windowWidthSpinBox;
};

#endif // SETTINGSSCREEN_H
